#!/usr/bin/env python3
"""Build station-logo SVGs that wrap *official* artwork.

Stations whose visual identity we can render faithfully with system
fonts are generated by `build_logos.py` (typographic approximations
extracted from the directory page tiles). For stations whose real logo
has a distinctive form we can't approximate well — scripted wordmarks,
illustrations, etc. — we instead bundle the actual artwork.

Source files live at `assets/official_logos/{key}_source.{ext}` and are
processed here into self-contained 256x256 SVGs at `pages/logos/{key}.svg`,
matching the same path convention used by every other station. SVG sources
are inlined as nested `<svg>`; raster sources (PNG/JPG) are base64-embedded
via `<image>`.

This script is the source of truth for the stations listed in OFFICIAL.
`build_logos.py` skips those keys so its tile-derived output never
overwrites the curated ones.

Run after editing source files or this script:

    python scripts/build_official_logos.py
"""
import base64
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
# Source artwork lives OUTSIDE pages/ so the deploy step (`cp -R pages/.
# output/`) doesn't ship the raw files alongside the rendered SVGs.
SRC_DIR = ROOT / "assets" / "official_logos"
OUT_DIR = ROOT / "pages" / "logos"


def main():
    builders = [
        ("wfmu", build_wfmu),
        ("radioparadise", build_radioparadise),
        ("nts", build_nts),
        ("vintageobscura", build_vintageobscura),
        ("bagelradio", build_bagelradio),
    ]
    for key, fn in builders:
        out = OUT_DIR / f"{key}.svg"
        out.write_text(fn())
        size = out.stat().st_size
        print(f"  ✓ {key}.svg ({size:,} bytes)")


# ----- per-station builders -----


def build_wfmu():
    """Black wordmark on a dark background — invert mark to white via fill override."""
    src = (SRC_DIR / "wfmu_source.svg").read_text()
    inner_paths = _extract_svg_paths(src, recolor_fills_to="#ffffff")
    src_viewbox = _extract_viewbox(src) or "0 0 636.59179 199.26709"
    # WFMU's wide aspect — render across most of the tile width with horizontal margins
    return _wrap(
        bg='<rect width="64" height="64" rx="14" ry="14" fill="#111111"/>',
        inner=(
            f'<svg x="6" y="22" width="52" height="20" '
            f'viewBox="{src_viewbox}" preserveAspectRatio="xMidYMid meet">'
            f'{inner_paths}'
            f'</svg>'
        ),
    )


def build_radioparadise():
    """RP's sun-and-RADIO-PARADISE mark on deep blue. Recolor grey paths to white
    so they read against the dark background; keep the gold accents (#f0b23e)."""
    src = (SRC_DIR / "rp_source.svg").read_text()
    # RP's <style> has .a{fill:#666667} (text/sigil grey) and .b{fill:#f0b23e} (gold).
    # Recolor `.a` to white; leave `.b` (gold) alone.
    src = src.replace("fill:#666667", "fill:#ffffff")
    inner_paths = _extract_svg_paths(src)
    src_viewbox = _extract_viewbox(src) or "0 0 401 105"
    # The mark has a circular "sun" sigil on the left + "RADIO PARADISE" wordmark on
    # the right. The whole thing has aspect ~3.8:1 — fit it across the tile center.
    return _wrap(
        bg=(
            '<defs><linearGradient id="g" x1="0%" y1="0%" x2="0%" y2="100%">'
            '<stop offset="0%" stop-color="#1c5480"/>'
            '<stop offset="100%" stop-color="#0F3B5F"/>'
            '</linearGradient></defs>'
            '<rect width="64" height="64" rx="14" ry="14" fill="url(#g)"/>'
        ),
        inner=(
            f'<svg x="4" y="24" width="56" height="16" '
            f'viewBox="{src_viewbox}" preserveAspectRatio="xMidYMid meet">'
            f'{inner_paths}'
            f'</svg>'
        ),
    )


def build_nts():
    """NTS's stylised mark on black."""
    src = (SRC_DIR / "nts_source.svg").read_text()
    inner_paths = _extract_svg_paths(src)
    src_viewbox = _extract_viewbox(src) or "-37 -37 100 100"
    return _wrap(
        bg='<rect width="64" height="64" rx="14" ry="14" fill="#000000"/>',
        inner=(
            f'<svg x="12" y="12" width="40" height="40" '
            f'viewBox="{src_viewbox}" preserveAspectRatio="xMidYMid meet">'
            f'{inner_paths}'
            f'</svg>'
        ),
    )


def build_vintageobscura():
    """Off-white VO badge embedded as raster on the sepia gradient bg."""
    data_url = _data_url(SRC_DIR / "vintageobscura_source.png", "image/png")
    return _wrap(
        bg=(
            '<defs><radialGradient id="g" cx="30%" cy="25%" r="75%">'
            '<stop offset="0%" stop-color="#8b6338"/>'
            '<stop offset="55%" stop-color="#6B4423"/>'
            '<stop offset="100%" stop-color="#3a2818"/>'
            '</radialGradient></defs>'
            '<rect width="64" height="64" rx="14" ry="14" fill="url(#g)"/>'
        ),
        # Source PNG aspect is 963:473 (~2:1), so center it horizontally
        inner=(
            f'<image x="6" y="20" width="52" height="26" '
            f'href="{data_url}" preserveAspectRatio="xMidYMid meet"/>'
        ),
    )


def build_bagelradio():
    """Bagel's full-color illustrated logo, embedded as JPG. The source has
    its own warm cream background baked in, so we just frame the whole image
    inside a rounded rect that masks to the tile shape."""
    data_url = _data_url(SRC_DIR / "bagelradio_source.jpg", "image/jpeg")
    return _wrap(
        bg='',  # The image fills the whole tile — no separate brand-color bg
        inner=(
            '<defs><clipPath id="c"><rect width="64" height="64" rx="14" ry="14"/></clipPath></defs>'
            f'<image x="0" y="0" width="64" height="64" '
            f'href="{data_url}" preserveAspectRatio="xMidYMid slice" clip-path="url(#c)"/>'
        ),
    )


# ----- helpers -----


def _wrap(bg, inner):
    """Wrap background + inner content in a 64x64 viewBox SVG at 256px."""
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" '
        'width="256" height="256" role="img" aria-label="Spinbin station logo">\n'
        f'  {bg}\n'
        f'  {inner}\n'
        '</svg>\n'
    )


def _extract_viewbox(svg):
    m = re.search(r'viewBox="([^"]+)"', svg)
    return m.group(1) if m else None


def _extract_svg_paths(svg, recolor_fills_to=None):
    """Strip the wrapping <svg>...</svg> and return inner content.
    Optionally recolor every `fill="…"` (and missing-fill paths) to a given hex."""
    m = re.search(r"<svg\b[^>]*>(.*)</svg>", svg, re.DOTALL)
    inner = m.group(1) if m else svg
    if recolor_fills_to:
        # Replace any explicit fill attribute on direct children
        inner = re.sub(r'\bfill="[^"]*"', f'fill="{recolor_fills_to}"', inner)
        # Apply the override to <path> elements that have no fill set
        inner = re.sub(
            r'<path(?![^>]*\bfill=)([^>]*)>',
            rf'<path fill="{recolor_fills_to}"\1>',
            inner,
        )
    return inner


def _data_url(path, mime):
    return f"data:{mime};base64,{base64.b64encode(path.read_bytes()).decode('ascii')}"


if __name__ == "__main__":
    main()
